# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: ["main"]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: "Hola, mundo"
        run: echo "Hello,World"

  messageSlack:
    runs-on: ubuntu-latest
    steps:
      - name: Notification Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: commits-dev
          SLACK_TITLE: Github notification
          SLACK_USERNAME: BotGithub
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "This is my first message"

  notifyTelegram:
    runs-on: ubuntu-latest
    steps:
      - name: Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            The ${{ github.event_name }} event triggered final step.
            echo This event is a pull request that had an assignee removed.
